name: ZZ-Build Tarball

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      pack-types:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack-type: ${{ fromJson(inputs.pack-types) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci

      - name: Install 7-Zip
        if: matrix.pack-type == 'tarballs'
        run: |
          sudo apt update
          sudo apt install p7zip-full p7zip-rar

      - name: Install makensis
        if: matrix.pack-type == 'win'
        run: |
          sudo apt update
          sudo apt install nsis

      - name: Build ${{ matrix.pack-type }}
        run: |
          ./node_modules/.bin/oclif pack ${{ matrix.pack-type }} ${{ matrix.pack-type == 'tarballs' && '--parallel' || '' }}

      - name: Package Info
        id: file-info
        run: |
          if [[ ${{ matrix.pack-type }} == 'tarballs' ]]; then
            echo "package_dir=" >> $GITHUB_OUTPUT
            echo "ext_glob=*.tar.*" >> $GITHUB_OUTPUT
          elif [[ ${{ matrix.pack-type }} == 'win' ]]; then
            echo "package_dir=win32/" >> $GITHUB_OUTPUT
            echo "ext_glob=*.exe" >> $GITHUB_OUTPUT
          elif [[ ${{ matrix.pack-type }} == 'deb' ]]; then
            echo "package_dir=${{ matrix.pack-type }}/" >> $GITHUB_OUTPUT
            echo "ext_glob=*.deb" >> $GITHUB_OUTPUT
          fi

      - name: Remove Hash
        run: |
          DIR="./dist/${{ steps.file-info.outputs.package_dir }}"
          SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          for file in $DIR/*$SHA-*; do mv "${file}" "${file/$SHA-/}"; done

      - name: Upload ${{ matrix.pack-type }} Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.version }}-${{ matrix.pack-type }}
          path: dist/${{ steps.file-info.outputs.package_dir }}${{ steps.file-info.outputs.ext_glob }}
