name: ZZ-publish-docker

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: griffincli/griffin-cli
          tags: type=semver,pattern={{version}},value=${{ inputs.version }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ vars.GRIFFIN_TEST_RUN != 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            "GRIFFIN_CLI_VERSION=${{ inputs.version }}"
