name: ZZ-Publish Release Artifacts

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      pack-types:
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack-type: ${{ fromJson(inputs.pack-types) }}
      fail-fast: false

    steps:
      - name: Download ${{ matrix.pack-type }} Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.version }}-${{ matrix.pack-type }}
          path: ./dist

      - name: Remove Hash
        run: |
          SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          for file in ./dist/*$SHA-*; do mv "${file}" "${file/$SHA-/}"; done

      - name: Update Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/*
          tag: ${{ inputs.version }}
          overwrite: true
          file_glob: true
