name: ZZ-Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run Unit Tests
        run: |
          npm run test:unit

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Up Env
        run: |
          npm run up

      - name: Run Integration Tests
        run: |
          npm run test:integration
