name: ZZ-Publish Release Artifacts

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      pack-types:
        type: string
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack-type: ${{ fromJson(inputs.pack-types) }}
      fail-fast: false

    steps:
      - name: Download ${{ matrix.pack-type }} Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.version }}-${{ matrix.pack-type }}

      - name: Update Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist${{ matrix.pack-type == 'tarballs' && '' || format('/{0}', matrix.pack-type) }}/*
          tag: ${{ inputs.version }}
          overwrite: true
          file_glob: true
