name: PR Standard Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    uses: ./.github/workflows/_helper-test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    uses: ./.github/workflows/_helper-lint.yml

  build:
    uses: ./.github/workflows/_helper-build.yml