name: PR Standard Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    uses: ./.github/workflows/_helper-test.yml

  lint:
    uses: ./.github/workflow/_helper-lint.yml

  build:
    uses: ./.github/workflow/_helper-build.yml