name: Release

on:
  release:
    types: [published]

  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to be published
        type: string
        required: true

concurrency:
  group: release

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - run: echo todo
